---
- name: systemd-boot_disable | Update /etc/kernel/cmdline
  become: true
  notify:
    - Update systemd-boot
    - Reboot host
  ansible.builtin.lineinfile:
    state: present
    dest: /etc/kernel/cmdline
    backrefs: true
    regexp: "{{ __regexp.pre }}{{ item }}{{ __regexp.post }}"
    line: "\\1\\3"
  loop: "{{ __cfg_keys }}"
  vars:
    __regexp:
      pre: '^(.*)\s*\b(\s'
      post: ')\b(.*)$'
#    - regexp: '^((?!.*\bamd_iommu=on\b))(.*)'
#      line: '\2 amd_iommu=on'
#    - regexp: '^((?!.*\biommu=pt\b))(.*)'
#      line: '\2 iommu=pt'
