---
- name: systemd-boot_disable | Update /etc/kernel/cmdline
  become: true
  notify:
    - 'pve_handlers : Refresh proxmox-boot-tool'
    - 'pve_handlers : Reboot host'
  ansible.builtin.lineinfile:
    state: present
    dest: /etc/kernel/cmdline
    backrefs: true
    regexp: "{{ __regexp.pre }}{{ item }}{{ __regexp.post }}"
    line: "\\1\\3"
  loop: "{{ __cfg_keys }}"
  vars:
    __regexp:
      pre: '^(.*)\s*\b(\s'
      post: ')\b(.*)$'
