---
- name: Configure repositories
  ansible.builtin.lineinfile:
    state: present
    path: "{{ item.path }}"
    line: "{{ '# ' if not (item.enabled | default(true) | bool) }}{{ item.line }}"
    regexp: "{{ item.regexp }}"
    create: true
    mode: '0644'
    owner: root
    group: root
  when: "item.when | default(true) | bool"
  loop_control:
    label: "{{ item.label }} - {{ 'Enabled' if item.enabled else 'Disabled' }}"
  loop:
    - label: "PVE enterprise"
      path: /etc/apt/sources.list.d/pve-enterprise.list
      regexp: "(.*)deb https://enterprise.proxmox.com/debian/pve (.*) pve-enterprise"
      line: "deb https://enterprise.proxmox.com/debian/pve {{ repo_distribution_release }} pve-enterprise"
      enabled: "{{ repo_enterprise | bool }}"
    - label: "PVE no-subscription"
      path: /etc/apt/sources.list.d/pve-install-repo.list
      regexp: "(.*)deb http://download.proxmox.com/debian/pve (.*) pve-no-subscription"
      line: "deb http://download.proxmox.com/debian/pve {{ repo_distribution_release }} pve-no-subscription"
      enabled: "{{ repo_no_subscription | bool }}"
    - label: "PVE Ceph enterprise"
      path: /etc/apt/sources.list.d/ceph.list
      when: "{{ ansible_distribution_major_version is version('12', '>=') }}"
      regexp: "(.*)deb http://enterprise.proxmox.com/debian/ceph-quincy (.*) enterprise"
      line: "deb http://enterprise.proxmox.com/debian/ceph-quincy {{ repo_distribution_release }} enterprise"
      enabled: "{{ (repo_ceph and repo_enterprise) | bool }}"
    - label: "PVE Ceph no-subscription"
      path: /etc/apt/sources.list.d/ceph.list
      when: "{{ ansible_distribution_major_version is version('12', '>=') }}"
      regexp: "(.*)deb http://download.proxmox.com/debian/ceph-quincy (.*) no-subscription"
      line: "deb http://download.proxmox.com/debian/ceph-quincy {{ repo_distribution_release }} no-subscription"
      enabled: "{{ (repo_ceph and repo_no_subscription) | bool }}"
