---
- name: grub_disable | Update /etc/default/grub
  become: true
  notify:
    - 'gvt_g : Update grub'
    - 'gvt_g : Reboot host'
  ansible.builtin.lineinfile:
    state: present
    dest: /etc/default/grub
    backrefs: true
    regexp: "{{ __regexp.pre }}{{ item }}{{ __regexp.post }}"
    line: "\\1\\3"
  loop: "{{ __cfg_keys }}"
  vars:
    __regexp:
      pre: '^(GRUB_CMDLINE_LINUX_DEFAULT=.*)\s*(\b'
      post: '\b)\s*(.*)$'
